/**
 * generated by Xtext 2.29.0
 */
package mgpl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import mgpl.MGPLRuntimeModule;
import mgpl.MGPLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MGPLIdeSetup extends MGPLStandaloneSetup {
  @Override
  public Injector createInjector() {
    MGPLRuntimeModule _mGPLRuntimeModule = new MGPLRuntimeModule();
    MGPLIdeModule _mGPLIdeModule = new MGPLIdeModule();
    return Guice.createInjector(Modules2.mixin(_mGPLRuntimeModule, _mGPLIdeModule));
  }
}
