/*
 * generated by Xtext 2.29.0
 */
package mgpl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMGPLScopeProvider extends DelegatingScopeProvider {
}
