/*
 * generated by Xtext 2.9.0
 */
package mgpl.tests

import com.google.inject.Inject
import mgpl.mGPL.Prog
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(MGPLInjectorProvider)
class MGPLParsingTest{

	@Inject
	ParseHelper<Prog> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
