/*
 * generated by Xtext 2.29.0
 */
package mgpl.ui;

import com.google.inject.Injector;
import mgpl.ui.internal.MgplActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MGPLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MgplActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MgplActivator activator = MgplActivator.getInstance();
		return activator != null ? activator.getInjector(MgplActivator.MGPL_MGPL) : null;
	}

}
