/**
 * generated by Xtext 2.9.0
 */
package mgpl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MGPLUiModule extends AbstractMGPLUiModule {
  public MGPLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
