/**
 * generated by Xtext 2.9.0
 */
package mgpl;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MGPLStandaloneSetup extends MGPLStandaloneSetupGenerated {
  public static void doSetup() {
    new MGPLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
