/**
 * generated by Xtext 2.29.0
 */
package mgpl.mGPL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>All Decls</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mgpl.mGPL.AllDecls#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see mgpl.mGPL.MGPLPackage#getAllDecls()
 * @model
 * @generated
 */
public interface AllDecls extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see mgpl.mGPL.MGPLPackage#getAllDecls_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link mgpl.mGPL.AllDecls#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // AllDecls
