/**
 * generated by Xtext 2.29.0
 */
package mgpl.mGPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mgpl.mGPL.MGPLPackage#getExpr()
 * @model
 * @generated
 */
public interface Expr extends Init
{
} // Expr
