/**
 * generated by Xtext 2.29.0
 */
package mgpl.mGPL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Init</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mgpl.mGPL.MGPLPackage#getInit()
 * @model
 * @generated
 */
public interface Init extends EObject
{
} // Init
